cmake_minimum_required(VERSION 3.22)
project(desktop-idle-status-plasmoid VERSION 0.1.0 LANGUAGES NONE)
find_package(ECM 6.0 REQUIRED NO_MODULE)
set(CMAKE_MODULE_PATH ${ECM_MODULE_PATH})
include(KDEInstallDirs6)
install(DIRECTORY contents DESTINATION ${KDE_INSTALL_DATADIR}/plasma/plasmoids/io.github.StantonMatt.DesktopIdleStatus)
install(FILES metadata.json DESTINATION ${KDE_INSTALL_DATADIR}/plasma/plasmoids/io.github.StantonMatt.DesktopIdleStatus)
install(FILES desktop-idle-status.notifyrc DESTINATION ${KDE_INSTALL_KNOTIFYRCDIR})
install(FILES io.github.StantonMatt.DesktopIdleStatus.desktop DESTINATION ${KDE_INSTALL_APPDIR})
install(FILES contents/icons/ready-32.svg DESTINATION ${KDE_INSTALL_ICONDIR}/hicolor/scalable/apps RENAME desktop-idle-status.svg)
